// Generated by https://quicktype.io

export interface Product {
  category: string;
  description: string;
  id: number;
  image: string;
  price: number;
  rating?: Rating;
  title: string;
}

export type ProductLike = Omit<Product, "id">;

export interface Rating {
  rate: number;
  count: number;
}
